[versions]

jline = "3.20.0"
jansi = "2.4.0"

[libraries]
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }

[plugins]