[versions]
jline = "3.23.0"
jansi = "2.4.0"
gson = "2.10.1"

# datbase
h2 = "2.2.220"

[libraries]
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# databse
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

[plugins]